spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/db/fruteria.db
    driver-class-name: org.sqlite.JDBC
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  