spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/db/fruteria.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
